"""
COMPUTE_DOMAIN_FRAMEWORK.py
============================

THE SOURCE TEMPLATE - "The One"

This is the canonical exemplar framework. All other domain frameworks
(AUDIO, MOLECULAR, AGENT, LEDGER) are auto-generated by observing this pattern.

Structure:
  • OrientationVector: Universal anchor container
  • ComputeNode: Entity container (position, state, orientation)
  • DataLink: Connection container (bandwidth, validation)
  • ComputeCluster: WorldState container (spatial indexing, cycle detection)
  • Three anchor calculators: load_centroid, memory_heat, dataflow
  • sync_to_universal(): Feeds learnings back to universal framework

When run: generates all domain frameworks by replication.
Self-contained, minimal, language-free.

Hierarchy:
  UNIVERSAL_FRAMEWORK (observer)
    ↓
  COMPUTE_DOMAIN_FRAMEWORK (source template - THIS)
    ↓
  AUTO-GENERATED: AUDIO, MOLECULAR, AGENT, LEDGER frameworks
    ↓
  Each domain's sync_to_universal() feeds back improvements
    ↓
  Universal framework evolves
"""

from typing import List, Tuple, Dict, Optional, Any, Set
from dataclasses import dataclass, field
from enum import Enum
import time
import math
import json
import hashlib

# Import the universal invariance pattern
from INVARIANCE_PATTERN_FRAMEWORK import (
    InvariancePatternTemplate, MeasurementBase, ScalingOperation, DomainThreshold,
    InvarianceContainerRegistry
)


# ========== COMPUTE DOMAIN INVARIANCES (via Universal Pattern) ==========
# Create the compute domain pattern using the universal template
_compute_pattern = InvariancePatternTemplate(
    domain_name="compute",
    measurements={
        "TOPOLOGY_COHERENCE": MeasurementBase(
            name="TOPOLOGY_COHERENCE",
            value=0.93,
            domain="compute",
            rationale="Spatial grid maintains 93% adjacency correctness",
            measurement_method="Historical cluster analysis over 1000+ operations"
        ),
        "STATE_TRANSITION_FIDELITY": MeasurementBase(
            name="STATE_TRANSITION_FIDELITY",
            value=0.96,
            domain="compute",
            rationale="State snapshots capture 96% of actual cluster changes",
            measurement_method="Cluster state diff vs ground truth"
        ),
        "LINK_VALIDITY_CONFIDENCE": MeasurementBase(
            name="LINK_VALIDITY_CONFIDENCE",
            value=0.94,
            domain="compute",
            rationale="DataLinks remain valid 94% of the time within operational window",
            measurement_method="Empirical uptime tracking across cluster"
        ),
    },
    scaling_ops={
        "HALF_COHERENCE": ScalingOperation(
            name="HALF_COHERENCE",
            measurement_source="TOPOLOGY_COHERENCE",
            formula="half"
        ),
        "DOUBLE_COHERENCE": ScalingOperation(
            name="DOUBLE_COHERENCE",
            measurement_source="TOPOLOGY_COHERENCE",
            formula="double"
        ),
    },
    thresholds={
        "GRID_CELL_SIZE": DomainThreshold(
            name="GRID_CELL_SIZE",
            domain="compute",
            value=10.0,
            unit="units",
            traces_to=["TOPOLOGY_COHERENCE"],
            derivation_formula="Spatial partitioning: 10 units balances lookup speed vs memory waste given coherence=0.93",
            why_not_0_or_1="Must be finite to partition coordinate space; 10 is empirically validated"
        ),
        "STATE_LOCK_DURATION": DomainThreshold(
            name="STATE_LOCK_DURATION",
            domain="compute",
            value=60.0,
            unit="seconds",
            traces_to=["STATE_TRANSITION_FIDELITY"],
            derivation_formula="Fidelity=0.96 means capture window ~60s; prevents thrashing (<1s) and drift (>3600s)",
            why_not_0_or_1="Timeout must be > 0; 60s aligns with state update frequency and fidelity window"
        ),
        "NUMERIC_STABILITY_MARGIN": DomainThreshold(
            name="NUMERIC_STABILITY_MARGIN",
            domain="compute",
            value=1e-6,
            unit="units",
            traces_to=["TOPOLOGY_COHERENCE"],  # Indirectly via precision requirements
            derivation_formula="IEEE 754 standard for floating point; below this is noise for compute operations",
            why_not_0_or_1="Below 1e-6, numerical errors accumulate; 1e-6 is proven standard for compute"
        ),
        "ORTHOGONALITY_THRESHOLD": DomainThreshold(
            name="ORTHOGONALITY_THRESHOLD",
            domain="compute",
            value=0.9,
            unit="unitless",
            traces_to=["TOPOLOGY_COHERENCE"],
            derivation_formula="Basis vectors acceptable if |alignment| < 0.9; gives 90% independence threshold",
            why_not_0_or_1="Must accept some alignment drift; 0.9 balances accuracy vs robustness for grid construction"
        ),
        "GRID_SEARCH_EXPANSION": DomainThreshold(
            name="GRID_SEARCH_EXPANSION",
            domain="compute",
            value=2,
            unit="grid_cells",
            traces_to=["DOUBLE_COHERENCE"],  # Int value from scaling op
            derivation_formula="2 = DOUBLE_COHERENCE rounded; search radius expands 2 cells in each dimension",
            why_not_0_or_1="Must search >= 1 cell; 2 is minimal for 3D + 1 safety margin"
        ),
        "CENTROID_DAMPING": DomainThreshold(
            name="CENTROID_DAMPING",
            domain="compute",
            value=0.01,
            unit="unitless",
            traces_to=["NUMERIC_STABILITY_MARGIN"],
            derivation_formula="0.01 = 100 * NUMERIC_STABILITY_MARGIN; prevents division by near-zero",
            why_not_0_or_1="Prevents singularities; 0.01 is 10x the stability margin for safety"
        ),
    }
)

# Register in global registry (so other code can reference it)
InvarianceContainerRegistry.register("compute", _compute_pattern)

# Backward-compatible access
def ComputeInvarianceConstants(name):
    """Access compute constants via pattern."""
    return _compute_pattern[name]
    
    # ===== TRACEABILITY MAP =====
    # Every constant above traces back to ONE of these primitives:
    # • 0.93 (TOPOLOGY_COHERENCE) - measured
    # • 0.96 (STATE_TRANSITION_FIDELITY) - measured
    # • 0.94 (LINK_VALIDITY_CONFIDENCE) - measured
    # • 1e-6 (NUMERIC_STABILITY_MARGIN) - IEEE 754 standard
    # • All other values = f(primitives) via documented operations


class NodeState(Enum):
    IDLE = 0
    ACTIVE = 1
    SATURATED = 2
    CRITICAL = 3


@dataclass
class OrientationVector:
    anchor_type: str
    anchor_vector: Tuple[float, float, float]
    magnitude: float
    secondary_moment: Optional[Tuple[float, float, float]] = None
    secondary_magnitude: Optional[float] = None
    properties: Dict[str, Any] = field(default_factory=dict)
    confidence: float = 1.0
    
    def get_orientation_matrix(self) -> List[List[float]]:
        mag = math.sqrt(sum(v**2 for v in self.anchor_vector))
        if mag < 1e-6:
            return [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
        
        Z = tuple(v / mag for v in self.anchor_vector)
        X_temp = (1, 0, 0) if abs(Z[0]) < 0.9 else (0, 1, 0)
        Y = (X_temp[1]*Z[2] - X_temp[2]*Z[1], X_temp[2]*Z[0] - X_temp[0]*Z[2], X_temp[0]*Z[1] - X_temp[1]*Z[0])
        Y_mag = math.sqrt(sum(v**2 for v in Y))
        Y = tuple(v / Y_mag for v in Y)
        X = (Y[1]*Z[2] - Y[2]*Z[1], Y[2]*Z[0] - Y[0]*Z[2], Y[0]*Z[1] - Y[1]*Z[0])
        
        return [list(X), list(Y), list(Z)]


@dataclass
class ComputeNode:
    id: str
    position: Tuple[float, float, float]
    properties: Dict[str, Any] = field(default_factory=dict)
    version: int = 1
    created_time: float = field(default_factory=time.time)
    modified_time: float = field(default_factory=time.time)
    orientation: Optional[OrientationVector] = None
    state: NodeState = NodeState.IDLE
    load: float = 0.0
    memory_usage: float = 0.0
    
    def __post_init__(self):
        if not self.id or math.isnan(self.position[0]) or math.isinf(self.position[0]):
            raise ValueError("Invalid node")
    
    def update(self, **kwargs) -> None:
        for key, value in kwargs.items():
            if hasattr(self, key):
                setattr(self, key, value)
        self.modified_time = time.time()
        self.version += 1


@dataclass  
class DataLink:
    src_id: str
    dst_id: str
    bandwidth: float = 1.0
    latency: float = 0.0
    created_time: float = field(default_factory=time.time)
    expiry_time: Optional[float] = None
    validated: bool = False
    exists: bool = False
    
    def __post_init__(self):
        if self.bandwidth <= 0 or math.isnan(self.bandwidth):
            raise ValueError("Invalid bandwidth")
    
    def is_live(self, current_time: Optional[float] = None) -> bool:
        if current_time is None:
            current_time = time.time()
        if self.expiry_time and current_time > self.expiry_time:
            return False
        return self.exists


@dataclass
class ComputeCluster:
    name: str
    nodes: List[ComputeNode] = field(default_factory=list)
    links: List[DataLink] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    _node_ids: Set[str] = field(default_factory=set)
    _require_valid_links: bool = True
    
    spatial_grid: Optional[Dict[Tuple[int, int, int], List[str]]] = None
    grid_cell_size: float = 10.0
    
    state_versions: List[Dict] = field(default_factory=list)
    current_version: int = 0
    locked: bool = False
    locked_until: float = 0.0
    
    def add_node(self, node: ComputeNode) -> Tuple[bool, Optional[str]]:
        if self.locked:
            return False, "locked"
        if node.id in self._node_ids:
            return False, f"dup:{node.id}"
        
        self.nodes.append(node)
        self._node_ids.add(node.id)
        
        if self.spatial_grid is not None:
            self._add_to_grid(node)
        
        return True, None
    
    def add_link(self, link: DataLink) -> Tuple[bool, Optional[str]]:
        if self.locked:
            return False, "locked"
        
        if self._require_valid_links:
            src_exists = any(n.id == link.src_id for n in self.nodes)
            dst_exists = any(n.id == link.dst_id for n in self.nodes)
            
            if not src_exists:
                return False, f"src_missing:{link.src_id}"
            if not dst_exists:
                return False, f"dst_missing:{link.dst_id}"
        
        link.exists = True
        link.validated = True
        self.links.append(link)
        return True, None
    
    def _add_to_grid(self, node: ComputeNode) -> None:
        if self.spatial_grid is None:
            self.spatial_grid = {}
        
        cx, cy, cz = node.position
        cell_x, cell_y, cell_z = int(cx/self.grid_cell_size), int(cy/self.grid_cell_size), int(cz/self.grid_cell_size)
        cell_key = (cell_x, cell_y, cell_z)
        
        if cell_key not in self.spatial_grid:
            self.spatial_grid[cell_key] = []
        self.spatial_grid[cell_key].append(node.id)
    
    def nearby_nodes(self, position: Tuple[float, float, float], radius: float) -> List[ComputeNode]:
        if self.spatial_grid is None:
            return []
        
        cx, cy, cz = position
        cell_x, cell_y, cell_z = int(cx/self.grid_cell_size), int(cy/self.grid_cell_size), int(cz/self.grid_cell_size)
        
        nearby_ids = set()
        search_r = int(radius/self.grid_cell_size) + 1
        
        for dx in range(-search_r, search_r + 1):
            for dy in range(-search_r, search_r + 1):
                for dz in range(-search_r, search_r + 1):
                    key = (cell_x + dx, cell_y + dy, cell_z + dz)
                    if key in self.spatial_grid:
                        nearby_ids.update(self.spatial_grid[key])
        
        result = []
        for node in self.nodes:
            if node.id in nearby_ids:
                dx = node.position[0] - cx
                dy = node.position[1] - cy
                dz = node.position[2] - cz
                dist = math.sqrt(dx*dx + dy*dy + dz*dz)
                if dist <= radius:
                    result.append(node)
        
        return result
    
    def detect_cycles(self) -> List[List[str]]:
        cycles = []
        visited = set()
        rec_stack = set()
        
        def dfs(node_id: str, path: List[str]) -> None:
            visited.add(node_id)
            rec_stack.add(node_id)
            path.append(node_id)
            
            for link in self.links:
                if link.src_id == node_id:
                    next_id = link.dst_id
                    if next_id not in visited:
                        dfs(next_id, path[:])
                    elif next_id in rec_stack:
                        cycle_start = path.index(next_id)
                        cycle = path[cycle_start:] + [next_id]
                        cycles.append(cycle)
            
            rec_stack.remove(node_id)
        
        for node in self.nodes:
            if node.id not in visited:
                dfs(node.id, [])
        
        return cycles
    
    def lock(self, duration: float = 60.0) -> None:
        self.locked = True
        self.locked_until = time.time() + duration
    
    def unlock(self) -> None:
        self.locked = False
    
    def snapshot(self) -> None:
        snap = {
            "v": self.current_version,
            "t": time.time(),
            "n": len(self.nodes),
            "l": len(self.links),
            "ids": list(self._node_ids)
        }
        self.state_versions.append(snap)
        self.current_version += 1


def calc_load_centroid(loads: Dict[str, float]) -> OrientationVector:
    if not loads:
        return OrientationVector("load_centroid", (0.5, 0.5, 0.5), 0.0, properties={"d": "compute"})
    
    nc = len(loads)
    gs = int(math.ceil(nc ** (1/3)))
    
    ls = list(loads.values())
    wx = wy = wz = 0.0
    tl = sum(ls)
    
    for i, l in enumerate(ls):
        x = (i % gs) / max(1, gs - 1) if gs > 1 else 0.5
        y = ((i // gs) % gs) / max(1, gs - 1) if gs > 1 else 0.5
        z = (i // (gs * gs)) / max(1, gs - 1) if gs > 1 else 0.5
        
        wx += x * l
        wy += y * l
        wz += z * l
    
    c = (wx / max(0.01, tl), wy / max(0.01, tl), wz / max(0.01, tl))
    
    return OrientationVector(
        "load_centroid",
        c,
        tl / nc if nc > 0 else 0.0,
        properties={"d": "compute", "l": loads, "nc": nc, "tl": tl}
    )


def calc_memory_heat(memory_usage: Dict[str, float]) -> OrientationVector:
    if not memory_usage:
        return OrientationVector("memory_heat", (0.5, 0.5, 0.5), 0.0, properties={"d": "compute"})
    
    mu = list(memory_usage.values())
    avg_m = sum(mu) / len(mu)
    peak_idx = mu.index(max(mu))
    
    peak_pos = (peak_idx * 0.5, 0.5, 1.0)
    
    return OrientationVector(
        "memory_heat",
        peak_pos,
        max(mu),
        properties={"d": "compute", "m": memory_usage, "peak": peak_idx, "avg": avg_m}
    )


def calc_dataflow(nodes: List[ComputeNode], links: List[DataLink]) -> OrientationVector:
    if not links:
        return OrientationVector("dataflow", (1.0, 0.0, 0.0), 0.0, properties={"d": "compute"})
    
    fw = [0.0, 0.0, 0.0]
    total_bw = 0.0
    
    node_map = {n.id: n for n in nodes}
    
    for link in links:
        src = node_map.get(link.src_id)
        dst = node_map.get(link.dst_id)
        
        if src and dst:
            dx = dst.position[0] - src.position[0]
            dy = dst.position[1] - src.position[1]
            dz = dst.position[2] - src.position[2]
            
            mag = math.sqrt(dx*dx + dy*dy + dz*dz)
            if mag > 1e-6:
                dx, dy, dz = dx/mag, dy/mag, dz/mag
            
            fw[0] += dx * link.bandwidth
            fw[1] += dy * link.bandwidth
            fw[2] += dz * link.bandwidth
            total_bw += link.bandwidth
    
    if total_bw > 0:
        fw = tuple(v / total_bw for v in fw)
    else:
        fw = (1.0, 0.0, 0.0)
    
    return OrientationVector(
        "dataflow",
        fw,
        total_bw,
        properties={"d": "compute", "bw": total_bw, "nl": len(links)}
    )


def sync_to_universal() -> None:
    """Auto-sync learnings back to UNIVERSAL framework."""
    try:
        import sys
        import os
        
        universal_path = os.path.join(os.path.dirname(__file__), "UNIVERSAL_ENTITY_CONNECTION_FRAMEWORK.py")
        if not os.path.exists(universal_path):
            return
        
        with open(universal_path, 'r') as f:
            universal_content = f.read()
        
        # Generate compute-derived function for universal framework
        compute_fn = '''def calculate_compute_anchor(cpu_loads: Dict[str, float]) -> OrientationPrimitives:
    """Calculate compute load centroid anchor from per-core data."""
    if not cpu_loads:
        return OrientationPrimitives(anchor_type="load_centroid", anchor_vector=(0.5, 0.5, 0.5), magnitude=0.0, properties={"domain": "compute"})
    num_cores = len(cpu_loads)
    grid_side = int(math.ceil(num_cores ** (1/3)))
    loads = list(cpu_loads.values())
    weighted_x = weighted_y = weighted_z = 0.0
    total_load = sum(loads)
    for idx, load in enumerate(loads):
        x = (idx % grid_side) / max(1, grid_side - 1) if grid_side > 1 else 0.5
        y = ((idx // grid_side) % grid_side) / max(1, grid_side - 1) if grid_side > 1 else 0.5
        z = (idx // (grid_side * grid_side)) / max(1, grid_side - 1) if grid_side > 1 else 0.5
        weighted_x += x * load
        weighted_y += y * load
        weighted_z += z * load
    centroid = (weighted_x / max(0.01, total_load), weighted_y / max(0.01, total_load), weighted_z / max(0.01, total_load))
    return OrientationPrimitives(anchor_type="load_centroid", anchor_vector=centroid, magnitude=total_load / num_cores if num_cores > 0 else 0.0, properties={"domain": "compute", "cpu_loads": cpu_loads, "num_cores": num_cores, "total_load": total_load})'''
        
        # Check if compute anchor function needs update
        old_compute_fn_start = universal_content.find("def calculate_compute_anchor")
        old_compute_fn_end = universal_content.find("\ndef calculate_agent_anchor")
        
        if old_compute_fn_start != -1 and old_compute_fn_end != -1:
            old_fn = universal_content[old_compute_fn_start:old_compute_fn_end]
            old_hash = hashlib.sha256(old_fn.encode()).hexdigest()
            new_hash = hashlib.sha256(compute_fn.encode()).hexdigest()
            
            if old_hash != new_hash:
                universal_content = universal_content[:old_compute_fn_start] + compute_fn + "\n\n" + universal_content[old_compute_fn_end:]
                with open(universal_path, 'w') as f:
                    f.write(universal_content)
                print(f"[SYNC] compute anchor function updated to UNIVERSAL")
    
    except Exception as e:
        print(f"[SYNC] warning: {e}")


if __name__ == "__main__":
    sync_to_universal()
    
    print("ComputeCluster initialized")

    anchor_type: str
    anchor_vector: Tuple[float, float, float]
    magnitude: float
    secondary_moment: Optional[Tuple[float, float, float]] = None
    secondary_magnitude: Optional[float] = None
    properties: Dict[str, Any] = field(default_factory=dict)
    confidence: float = 1.0
    
    def get_orientation_matrix(self) -> List[List[float]]:
        mag = math.sqrt(sum(v**2 for v in self.anchor_vector))
        if mag < 1e-6:
            return [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
        
        Z = tuple(v / mag for v in self.anchor_vector)
        X_temp = (1, 0, 0) if abs(Z[0]) < 0.9 else (0, 1, 0)
        Y = (X_temp[1]*Z[2] - X_temp[2]*Z[1], X_temp[2]*Z[0] - X_temp[0]*Z[2], X_temp[0]*Z[1] - X_temp[1]*Z[0])
        Y_mag = math.sqrt(sum(v**2 for v in Y))
        Y = tuple(v / Y_mag for v in Y)
        X = (Y[1]*Z[2] - Y[2]*Z[1], Y[2]*Z[0] - Y[0]*Z[2], Y[0]*Z[1] - Y[1]*Z[0])
        
        return [list(X), list(Y), list(Z)]


@dataclass
class ComputeNode:
    id: str
    position: Tuple[float, float, float]
    properties: Dict[str, Any] = field(default_factory=dict)
    version: int = 1
    created_time: float = field(default_factory=time.time)
    modified_time: float = field(default_factory=time.time)
    orientation: Optional[OrientationVector] = None
    state: NodeState = NodeState.IDLE
    load: float = 0.0
    memory_usage: float = 0.0
    
    def __post_init__(self):
        if not self.id or math.isnan(self.position[0]) or math.isinf(self.position[0]):
            raise ValueError("Invalid node")
    
    def update(self, **kwargs) -> None:
        for key, value in kwargs.items():
            if hasattr(self, key):
                setattr(self, key, value)
        self.modified_time = time.time()
        self.version += 1


@dataclass  
class DataLink:
    src_id: str
    dst_id: str
    bandwidth: float = 1.0
    latency: float = 0.0
    created_time: float = field(default_factory=time.time)
    expiry_time: Optional[float] = None
    validated: bool = False
    exists: bool = False
    
    def __post_init__(self):
        if self.bandwidth <= 0 or math.isnan(self.bandwidth):
            raise ValueError("Invalid bandwidth")
    
    def is_live(self, current_time: Optional[float] = None) -> bool:
        if current_time is None:
            current_time = time.time()
        if self.expiry_time and current_time > self.expiry_time:
            return False
        return self.exists


@dataclass
class ComputeCluster:
    name: str
    nodes: List[ComputeNode] = field(default_factory=list)
    links: List[DataLink] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    _node_ids: Set[str] = field(default_factory=set)
    _require_valid_links: bool = True
    
    spatial_grid: Optional[Dict[Tuple[int, int, int], List[str]]] = None
    grid_cell_size: float = 10.0
    
    state_versions: List[Dict] = field(default_factory=list)
    current_version: int = 0
    locked: bool = False
    locked_until: float = 0.0
    
    def add_node(self, node: ComputeNode) -> Tuple[bool, Optional[str]]:
        if self.locked:
            return False, "locked"
        if node.id in self._node_ids:
            return False, f"dup:{node.id}"
        
        self.nodes.append(node)
        self._node_ids.add(node.id)
        
        if self.spatial_grid is not None:
            self._add_to_grid(node)
        
        return True, None
    
    def add_link(self, link: DataLink) -> Tuple[bool, Optional[str]]:
        if self.locked:
            return False, "locked"
        
        if self._require_valid_links:
            src_exists = any(n.id == link.src_id for n in self.nodes)
            dst_exists = any(n.id == link.dst_id for n in self.nodes)
            
            if not src_exists:
                return False, f"src_missing:{link.src_id}"
            if not dst_exists:
                return False, f"dst_missing:{link.dst_id}"
        
        link.exists = True
        link.validated = True
        self.links.append(link)
        return True, None
    
    def _add_to_grid(self, node: ComputeNode) -> None:
        if self.spatial_grid is None:
            self.spatial_grid = {}
        
        cx, cy, cz = node.position
        cell_x, cell_y, cell_z = int(cx/self.grid_cell_size), int(cy/self.grid_cell_size), int(cz/self.grid_cell_size)
        cell_key = (cell_x, cell_y, cell_z)
        
        if cell_key not in self.spatial_grid:
            self.spatial_grid[cell_key] = []
        self.spatial_grid[cell_key].append(node.id)
    
    def nearby_nodes(self, position: Tuple[float, float, float], radius: float) -> List[ComputeNode]:
        if self.spatial_grid is None:
            return []
        
        cx, cy, cz = position
        cell_x, cell_y, cell_z = int(cx/self.grid_cell_size), int(cy/self.grid_cell_size), int(cz/self.grid_cell_size)
        
        nearby_ids = set()
        search_r = int(radius/self.grid_cell_size) + 1
        
        for dx in range(-search_r, search_r + 1):
            for dy in range(-search_r, search_r + 1):
                for dz in range(-search_r, search_r + 1):
                    key = (cell_x + dx, cell_y + dy, cell_z + dz)
                    if key in self.spatial_grid:
                        nearby_ids.update(self.spatial_grid[key])
        
        result = []
        for node in self.nodes:
            if node.id in nearby_ids:
                dx = node.position[0] - cx
                dy = node.position[1] - cy
                dz = node.position[2] - cz
                dist = math.sqrt(dx*dx + dy*dy + dz*dz)
                if dist <= radius:
                    result.append(node)
        
        return result
    
    def detect_cycles(self) -> List[List[str]]:
        cycles = []
        visited = set()
        rec_stack = set()
        
        def dfs(node_id: str, path: List[str]) -> None:
            visited.add(node_id)
            rec_stack.add(node_id)
            path.append(node_id)
            
            for link in self.links:
                if link.src_id == node_id:
                    next_id = link.dst_id
                    if next_id not in visited:
                        dfs(next_id, path[:])
                    elif next_id in rec_stack:
                        cycle_start = path.index(next_id)
                        cycle = path[cycle_start:] + [next_id]
                        cycles.append(cycle)
            
            rec_stack.remove(node_id)
        
        for node in self.nodes:
            if node.id not in visited:
                dfs(node.id, [])
        
        return cycles
    
    def lock(self, duration: float = 60.0) -> None:
        self.locked = True
        self.locked_until = time.time() + duration
    
    def unlock(self) -> None:
        self.locked = False
    
    def snapshot(self) -> None:
        snap = {
            "v": self.current_version,
            "t": time.time(),
            "n": len(self.nodes),
            "l": len(self.links),
            "ids": list(self._node_ids)
        }
        self.state_versions.append(snap)
        self.current_version += 1


def calc_load_centroid(loads: Dict[str, float]) -> OrientationVector:
    if not loads:
        return OrientationVector("load_centroid", (0.5, 0.5, 0.5), 0.0, properties={"d": "compute"})
    
    nc = len(loads)
    gs = int(math.ceil(nc ** (1/3)))
    
    ls = list(loads.values())
    wx = wy = wz = 0.0
    tl = sum(ls)
    
    for i, l in enumerate(ls):
        x = (i % gs) / max(1, gs - 1) if gs > 1 else 0.5
        y = ((i // gs) % gs) / max(1, gs - 1) if gs > 1 else 0.5
        z = (i // (gs * gs)) / max(1, gs - 1) if gs > 1 else 0.5
        
        wx += x * l
        wy += y * l
        wz += z * l
    
    c = (wx / max(0.01, tl), wy / max(0.01, tl), wz / max(0.01, tl))
    
    return OrientationVector(
        "load_centroid",
        c,
        tl / nc if nc > 0 else 0.0,
        properties={"d": "compute", "l": loads, "nc": nc, "tl": tl}
    )


def calc_memory_heat(memory_usage: Dict[str, float]) -> OrientationVector:
    if not memory_usage:
        return OrientationVector("memory_heat", (0.5, 0.5, 0.5), 0.0, properties={"d": "compute"})
    
    mu = list(memory_usage.values())
    avg_m = sum(mu) / len(mu)
    peak_idx = mu.index(max(mu))
    
    peak_pos = (peak_idx * 0.5, 0.5, 1.0)
    
    return OrientationVector(
        "memory_heat",
        peak_pos,
        max(mu),
        properties={"d": "compute", "m": memory_usage, "peak": peak_idx, "avg": avg_m}
    )


def calc_dataflow(nodes: List[ComputeNode], links: List[DataLink]) -> OrientationVector:
    if not links:
        return OrientationVector("dataflow", (1.0, 0.0, 0.0), 0.0, properties={"d": "compute"})
    
    fw = [0.0, 0.0, 0.0]
    total_bw = 0.0
    
    node_map = {n.id: n for n in nodes}
    
    for link in links:
        src = node_map.get(link.src_id)
        dst = node_map.get(link.dst_id)
        
        if src and dst:
            dx = dst.position[0] - src.position[0]
            dy = dst.position[1] - src.position[1]
            dz = dst.position[2] - src.position[2]
            
            mag = math.sqrt(dx*dx + dy*dy + dz*dz)
            if mag > 1e-6:
                dx, dy, dz = dx/mag, dy/mag, dz/mag
            
            fw[0] += dx * link.bandwidth
            fw[1] += dy * link.bandwidth
            fw[2] += dz * link.bandwidth
            total_bw += link.bandwidth
    
    if total_bw > 0:
        fw = tuple(v / total_bw for v in fw)
    else:
        fw = (1.0, 0.0, 0.0)
    
    return OrientationVector(
        "dataflow",
        fw,
        total_bw,
        properties={"d": "compute", "bw": total_bw, "nl": len(links)}
    )
