source 'https://rubygems.org'

gem 'jekyll', '~> 4.3'
gem 'minima', '~> 2.5'
gem 'jekyll-default-layout'
gem 'jekyll-relative-links'

group :jekyll_plugins do
  gem 'jekyll-feed'
  gem 'jekyll-seo-tag'
  gem 'jekyll-sitemap'
end
