source 'https://rubygems.org'

gem 'jekyll', '~> 4.3'
gem 'minima', '~> 2.5'
gem 'jekyll-feed'
gem 'jekyll-seo-tag'
gem 'jekyll-sitemap'
gem 'jekyll-default-layout'
gem 'jekyll-relative-links'

group :jekyll_plugins do
  gem 'jekyll-feed'
  gem 'jekyll-seo-tag'
  gem 'jekyll-sitemap'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
platforms :mingw, :mswin, :x64_mingw, :jruby do
  gem 'tzinfo', '>= 1', '< 3'
  gem 'tzinfo-data'
end

gem 'wdm', '~> 0.1.1', :platforms => [:mingw, :mswin, :x64_mingw]
